name: â˜ï¸ Release NPM

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  npm:
    name: â˜ï¸ Release NPM
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v6

      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: ğŸ› ï¸ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          cache: 'pnpm'

      - name: âš¡ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ”¨ Build library
        run: pnpm build:lib

      - name: ğŸ“¦ Pack library
        run: pnpm pack --out package.tgz

      - name: â˜ï¸ Publish to npm (OIDC)
        run: npm publish package.tgz --provenance --access public

      - name: â˜ï¸ Create a release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: Release ${{ github.ref_name }}
          files: package.tgz
